# Generated by Django 5.2.5 on 2025-08-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grades',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
